bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>/', views.delete_product, name='delete_product'
        ),
    path(
        'product/<int:product_id>/add-to-favorites/',
        views.add_to_favorites, name='add_to_favorites'),
    path(
        'favorites/<int:product_id>/remove/',
        views.remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

yoga_vibe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('products/', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'yoga_vibe.views.handler404'

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


# Create your models here.
class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = (
            self.lineitems
            .aggregate(Sum('lineitem_total'))
            ['lineitem_total__sum'] or 0
            )
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total *
                settings.STANDARD_DELIVERY_PERCENTAGE / 100
                )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number

    def get_first_name(self):
        return self.full_name.split(' ')[0]


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems'
        )
    product = models.ForeignKey(
        Product, null=False,
        blank=False, on_delete=models.CASCADE
        )
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False,
        blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """
    Represents a category for grouping products.
    """

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    """
    Represents a product available for sale.
    """

    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock_quantity = models.PositiveIntegerField(default=10)
    rating = models.DecimalField(
        max_digits=6, decimal_places=1, null=True, blank=True)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    image1 = models.ImageField(
        upload_to='product_imgs/',
        default='product_imgs/noimage.png',
        null=True, blank=True
    )
    image2 = models.ImageField(
        upload_to='product_imgs/',
        null=True, blank=True
    )
    image3 = models.ImageField(
        upload_to='product_imgs/',
        null=True, blank=True
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.image1 and not self.image2 and not self.image3:
            self.image1 = 'product_imgs/noimage.png'

        super().save(*args, **kwargs)


class ProductRecommendation(models.Model):
    product = models.ForeignKey(
        Product, related_name='main_product', on_delete=models.CASCADE
    )
    recommended_product = models.ForeignKey(
        Product, related_name='recommended_product', on_delete=models.CASCADE
    )

    def __str__(self):
        return (
            f'{self.product.name} recommends '
            f'{self.recommended_product.name}'
        )



class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return f'{self.user.username} - {self.product.name}'


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    title = models.CharField(max_length=100)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.user.username} for {self.product.name}'

products/forms.py
from django import forms
from .models import Product, Category, Review


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'title', 'comment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].required = True  # Ensure title is required

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.urls import reverse
from .models import Product, Category, Favorite, Review, ProductRecommendation
from .forms import ProductForm, ReviewForm


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    print("all products", products)
    query = None
    categories = None

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

            if not products.exists():
                messages.error(request, "No products found matching your search criteria.")
                return redirect(reverse('products'))

    context = {
        'products': products,
        'search_term': query,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details and handle reviews """
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)
    is_favorite = False
    recommended_products = (
        Product.objects
        .filter(category=product.category)
        .exclude(id=product_id)
        [:4]
    )

    if request.user.is_authenticated:
        is_favorite = (
            Favorite.objects
            .filter(user=request.user, product=product)
            .exists()
        )

        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.user = request.user
                review.save()
                messages.success(request, 'Your review has been submitted!')
                return redirect('product_detail', product_id=product.id)
            else:
                messages.error(request, 'There was an error with your review.')
        else:
            form = ReviewForm()
    else:
        form = None

    context = {
        'product': product,
        'reviews': reviews,
        'is_favorite': is_favorite,
        'review_form': form,
        'recommended_products': recommended_products,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.'
            )
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.'
            )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


def add_to_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        favorite, created = Favorite.objects.get_or_create(
            user=request.user,
            product=product
        )
        if created:
            messages.success(
                request,
                'Product added to favorites successfully.'
            )
        else:
            favorite.delete()
            messages.success(request, 'Product removed from favorites.')

        return redirect(reverse('product_detail', args=[product_id]))

    else:
        messages.warning(request, 'Please login to add to favorites.')
        return redirect(reverse('product_detail', args=[product_id]))


def remove_from_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        try:
            favorite = Favorite.objects.get(user=request.user, product=product)
            favorite.delete()
            messages.success(
                request,
                'Product removed from favorites successfully.'
            )
        except Favorite.DoesNotExist:
            messages.error(request, 'Product is not in your favorites.')
        except Exception as e:
            messages.error(
                request,
                f'Error removing product from favorites: {str(e)}'
            )

        return redirect(reverse('favorite_list'))

    else:
        messages.warning(request, 'Please login to remove from favorites.')
        return redirect(reverse('product_detail', args=[product_id]))


@login_required
def favorite_list(request):
    favorites = Favorite.objects.filter(user=request.user)
    context = {
        'favorites': favorites,
        'on_favorite_page': True,
    }
    return render(request, 'products/favorites.html', context)

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container custom-product-form text-black">
    <div class="row justify-content-center">
        <div class="col-10 col-md-8 text-center">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="logo-font text-center">Add a Product</h5>
            <hr>
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center pt-4 pb-3">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row justify-content-center">
        <div class="col text-center"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container custom-product-form text-black text-center">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-black logo-font text-center">Edit a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center pt-4 pb-4">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static account %}
{% load star_rating %}
{% load humanize %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                <div id="carouselExample" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% if product.image1 %}
                        <div class="carousel-item active">
                            <a href="{{ product.image1.url }}" target="_blank">
                                <img class="d-block w-100" src="{{ product.image1.url }}" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% endif %}
                        {% if product.image2 %}
                        <div class="carousel-item">
                            <a href="{{ product.image2.url }}" target="_blank">
                                <img class="d-block w-100" src="{{ product.image2.url }}" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% endif %}
                        {% if product.image3 %}
                        <div class="carousel-item">
                            <a href="{{ product.image3.url }}" target="_blank">
                                <img class="d-block w-100" src="{{ product.image3.url }}" alt="{{ product.name }}">
                            </a>
                        </div>
                        {% endif %}
                    </div>
                    {% if product.image2 or product.image3 %}
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <div class="row align-items-center">
                    <div class="col-8">
                        <p class="mb-0 text-uppercase" id="product-name">{{ product.name }}</p>
                    </div>
                    <div class="col-4 text-right">
                        <form action="{% url 'add_to_favorites' product.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="favorite-btn">
                                {% if user.is_authenticated %}
                                {% if is_favorite %}
                                <i class="fa-solid fa-heart"></i>
                                {% else %}
                                <i class="fa-regular fa-heart"></i>
                                {% endif %}
                                {% else %}
                                <i class="fa-regular fa-heart"></i>
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>

                <p class="lead mb-0 text-left font-weight-bold">${{ product.price | intcomma }}</p>
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
                {% if request.user.is_superuser %}
                <small class="ml-3">
                    <a href="{% url 'edit_product' product.id %}" class="text-primary text-decoration-none">Edit </a> |
                    <a class="text-danger text-decoration-none" href="{% url 'delete_product' product.id %}"> Delete</a>
                </small>
                {% endif %}
                <p class="mt-3">{{ product.description | safe }}</p>

                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                <option value="s" selected>S</option>
                                <option value="m">M</option>
                                <option value="l">L</option>
                            </select>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-black rounded"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-black rounded"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Recommended Products Section -->
    <div class="row mt-4">
        <div class="col-12">
            <h3 class="pb-3 text-center text-uppercase">Recommended Products</h3>
            <div class="row justify-content-center">
                {% for recommended_product in recommended_products %}
                <div class="col-12 col-md-6 col-lg-3 mb-4 text-center">
                    <div class="h-100">
                        <a href="{% url 'product_detail' recommended_product.id %}">
                            <img class="card-img-top recommended-product-img" src="{{ recommended_product.image1.url }}"
                                alt="{{ recommended_product.name }}">
                        </a>
                        <div class=" pt-3 card">
                            <h5 class="card-title">{{ recommended_product.name }}</h5>
                            <p class="card-text">${{ recommended_product.price }}</p>
                            <a href="{% url 'product_detail' recommended_product.id %}"
                                class="btn btn-black rounded-0">View Product</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Reviews Section -->
    <div class="row mt-4">
        <div class="col-12">
            <h3 class="text-center text-uppercase">Reviews {% if reviews.count > 0 %}({{ reviews.count }}){% endif %}
            </h3>
            {% if user.is_authenticated %}
            <div class="text-center text-md-end">
                <button class="btn mt-4 btn text-uppercase btn-black rounded-0" type="button" data-toggle="collapse"
                    data-target="#reviewForm" aria-expanded="false" aria-controls="reviewForm">
                    Write a Review
                </button>
            </div>

            <div class="collapse mt-4" id="reviewForm">
                <div class="card card-body">
                    <form method="post" action="{% url 'product_detail' product.id %}">
                        {% csrf_token %}
                        {{ review_form.as_p }}
                        <button type="submit" class="btn text-uppercase btn-black rounded-0">Submit Review</button>
                    </form>
                </div>
            </div>
            {% else %}
            <p class="text-center text-md-end">Please <a href="{% url 'account_login' %}">log in</a> to add a review.
            </p>
            {% endif %}
        </div>
        <div class="col-12 mt-4">
            <div id="reviews-container">
                {% for review in reviews %}
                <div class="mb-3 review {% if forloop.counter > 4 %}d-none{% endif %}">
                    <div class="card-body ps-5">
                        <h5 class="card-title">{{ review.user.username }}</h5>
                        <p class="card-text">{% star_rating review.rating %}</p>
                        <p id="review-title">{{ review.title }}</p>
                        <p class="card-text">{{ review.comment }}</p>
                        <p class="card-text"><small class="text-muted">{{ review.created_at }}</small></p>
                    </div>
                </div>
                {% empty %}
                <p class="text-center text-md-end">No reviews yet.</p>
                {% endfor %}
            </div>
            {% if reviews.count > 4 %}
            <div class="text-center">
                <button id="show-more-reviews" class="btn text-uppercase btn-black rounded-0">Show More</button>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input.html' %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const showMoreButton = document.getElementById('show-more-reviews');
        if (showMoreButton) {
            let visibleReviews = 4;

            showMoreButton.addEventListener('click', function () {
                const hiddenReviews = document.querySelectorAll('.review.d-none');
                for (let i = 0; i < 4 && i < hiddenReviews.length; i++) {
                    hiddenReviews[i].classList.remove('d-none');
                }
                visibleReviews += 4;
                if (visibleReviews >= document.querySelectorAll('.review').length) {
                    showMoreButton.classList.add('d-none');
                }
            });
        }
    });
</script>
{% endblock %}